SELECT     VI_SUBACTIVIDADES.CODIGO, VI_SUBACTIVIDADES.ACTIVIDAD, VI_SUBACTIVIDADES.NOMBRE, VI_SUBACTIVIDADES.COD_EQUIPO, 
                      VI_SUBACTIVIDADES.COD_ACTIVIDAD, AO.IND_EJECUTADO, FECHA
FROM      VI_SUBACTIVIDADES LEFT OUTER JOIN
		 (SELECT  ACTIVIDADES_OT.COD_SUB_ACTIVIDAD, ACTIVIDADES_OT.FOLIO_OT,
				  ACTIVIDADES_OT.CODIGO_ACTIVIDAD, ACTIVIDADES_OT.IND_EJECUTADO, ACTIVIDADES_OT.FECHA
			FROM ACTIVIDADES_OT WHERE ACTIVIDADES_OT.FOLIO_OT = 2) AS AO
		  ON VI_SUBACTIVIDADES.CODIGO = AO.COD_SUB_ACTIVIDAD
		 AND VI_SUBACTIVIDADES.COD_ACTIVIDAD = AO.CODIGO_ACTIVIDAD
WHERE     (VI_SUBACTIVIDADES.COD_EQUIPO = 'G1.1.3') 