	SELECT	B.ID AS ID, B.FECHA , B.TURNO, B.RESPONSABLE, 
	 DATEDIFF([DAY],  b.fecha, getdate()),
	B.DESCRIPCION, B.EQUIPO, E.DESCRIPCION AS DESC_EQUIPO,
	B.ESTADO, B.IND_INCIDENTE, day(getdate()-b.fecha)
	FROM BITACORAS AS B, EQUIPOS AS E 
	WHERE B.IND_INCIDENTE='TRUE'
			AND B.EQUIPO=E.CODIGO