SELECT     E.CODIGO, E.DESCRIPCION, E.FECHA_ASIGNADO, OT.FECHA_PROGRAMADA, E.HOROMETRO, E.HOROMETRO_VEN, E.RESPONSABLE_MAN, 
                      OT.FOLIO_OT, OT.TURNO
FROM         Equipos AS E LEFT OUTER JOIN
                      OT ON E.CODIGO = OT.EQUIPO
WHERE     (E.ESTADO = 'ASG')