
SELECT  AÑO, MES, EQUIPO, COD_SUBEQUIPO, SUBEQUIPO, ELEMENTO,
		VALOR AS HOROMETRO_FALLA,
		CASE 
		WHEN dbo.LastValue(COD_SUBEQUIPO,CONVERT(CHAR,FECHA,103)) is null THEN '0'
		ELSE VALOR - dbo.LastValue(COD_SUBEQUIPO,CONVERT(CHAR,FECHA,103)) END
		AS HORAS
FROM HOROMETRO_INCIDENTE








		


