	SELECT  M.FOLIO, RTRIM(CONVERT(CHAR, M.FECHA, 103)) + ' ' + 
	 substring(convert(char,M.FECHA,108),1,5) AS FECHA, ING.TIPO_DOC, ING.NRO_DOCUMENTO, 
		  ENTRADAS = CASE M.TIPO WHEN 'ING' THEN CANTIDAD END,
		  SALIDAS = CASE M.TIPO WHEN 'SAL' THEN CANTIDAD END,
		  M.SALDO, M.VALORIZACION, CAST(M.PPM AS DECIMAL(16,2)) 
	 FROM      MOVIMIENTOS AS M
	 LEFT OUTER JOIN INGRESOS AS ING ON ING.FOLIO=M.FOLIO AND M.TIPO='ING' 
	 LEFT OUTER JOIN EGRESOS AS EGR ON EGR.FOLIO=M.FOLIO AND M.TIPO='SAL' 
	 WHERE M.COD_ARTICULO =2023
			  AND M.FECHA >= '01/01/2008'
			  AND M.FECHA <= '30/11/2008'
	 GROUP BY M.FOLIO, M.FECHA, M.TIPO, ING.TIPO_DOC, ING.NRO_DOCUMENTO, 
	CANTIDAD, M.SALDO, M.VALORIZACION	, M.PPM 
	 ORDER BY CAST(M.FECHA AS DATETIME) ASC

execute CalculoSaldo 2023, 09, 2008