SELECT  A.ID, A.DESCRIPCION,
		SALDO =	SUM(CASE WHEN (M.TIPO='ING' 
								AND CONVERT(FLOAT,SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2))<6)
								THEN CANTIDAD ELSE 0 END)-
				SUM(CASE WHEN (M.TIPO='SAL' 
								AND CONVERT(FLOAT,SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2))<6)
								THEN CANTIDAD ELSE 0 END),
		ENTRADAS = SUM(CASE WHEN (M.TIPO='ING'
								AND CONVERT(FLOAT,SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2))=6)
								THEN CANTIDAD ELSE 0 END),
		SALIDAS = SUM(CASE WHEN (M.TIPO='SAL'
								AND CONVERT(FLOAT,SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2))=6)
								 THEN CANTIDAD ELSE 0 END),
		dbo.GetPPM(A.ID), M.UBICACION 
	  FROM     MOVIMIENTOS AS M, 
	 		   ARTICULOS AS A 
	  WHERE  A.ID=M.COD_ARTICULO
			AND CONVERT(FLOAT,SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2)) <= 6
	 		AND SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),7,4)='2008'
	  GROUP BY  A.ID,  A.DESCRIPCION,
				M.UBICACION
	 ORDER BY A.DESCRIPCION
	  --ORDER BY SUBSTRING(RTRIM(CONVERT(CHAR,M.FECHA,103)),4,2)